child/urls.py
from django.urls import path
from .views import HomePageView#,PostDetailView,AddPostView,primeview
from django.conf.urls.static import static
from .views import *

app_name = 'child'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('calculus1/', Calculus1.as_view(), name='cal1'),
    path('algebra1/', Algebra1.as_view(), name='alg1'),
    path('probablity1/', Probability1.as_view(), name='pro1'),
    path('statictics1/', Statictics1.as_view(), name='sta1'),
    path('calculus2/', Calculus2.as_view(), name='cal2'),
    path('algebra2/', Algebra2.as_view(), name='alg2'),
    path('probablity2/', Probability2.as_view(), name='pro2'),
    path('statictics2/', Statistics2.as_view(), name='sta2'),
    path('about/', About.as_view(), name='about'),

]

mysite/urls.py
from argparse import Namespace
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from child import urls as child_urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(child_urls, namespace='child')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

child/models.py
from django.db import models

# Create your models here.

child/views.py
from http.client import HTTPResponse
from urllib import request
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
from re import X, template
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView,FormView
# from .models import Post
# from .form import PostForm
# from django.contrib import messages
import sympy

x = sympy.Symbol('x')
y = sympy.Symbol('y')
z = sympy.Symbol('z')





# Create your views here.
class HomePageView(TemplateView):
        template_name = 'web.html'



class Calculus1(TemplateView):
    #template_name = 'calculus_form.html'
    def get(self, request):
        return render(request, 'calculus_form.html')

    def post(self, request):
        x = request.POST.get('x')
        respect = request.POST.get('respect')
        order = int(request.POST.get('order'))
        equ = x 
        result = sympy.diff(equ, respect, order)
        return render(request, 'calculus_form.html', {'result': result})

class Algebra1(TemplateView):
    # template_name = 'algebra_form.html'
    def get(self, request):
        return render(request, 'algebra_form.html')

    def post(self, request):
        x = request.POST.get('x')
        print("x:", x)
        result = sympy.simplify(x)
        return render(request, 'algebra_form.html', {'result': result})



class Probability1(TemplateView):
    # template_name = 'probability_form.html'

    def get(self, request):
        return render(request, 'probability_form.html')

    def post(self, request):
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        print('x, x')
        print('y:' ,y)


        ans = x/y
        result = ans
        return render(request, 'probability_form.html', {'result': result})




class Statictics1(TemplateView):
    # template_name = 'statistic_form.html'

    def get(self, request):
        return render(request, 'statistic_form.html')

    def post(self, request):
        x = request.POST.get('x')
        
        list = x.split()

        sorted_numbers = sorted(list)
        length = len(sorted_numbers)

        if length % 2 == 0:
            mid1 = sorted_numbers[length // 2]
            mid2 = sorted_numbers[length // 2 - 1]
            median = (mid1 + mid2) / 2
        else:
            median = sorted_numbers[length // 2]

        result = median

        return render(request, 'statistic_form.html', {'result': result})


print('#########################################')

class Calculus2(TemplateView):
    template_name = 'calculus1.html'

class Algebra2(TemplateView):
    template_name = 'algebra1.html'

class Probability2(TemplateView):
    template_name = 'probability1.html'

class Statistics2(TemplateView):
    template_name = 'statistics1.html'

class About(TemplateView):
    template_name = 'about.html'

templates/about.html
{% extends "base.html" %}
{% block title %} About  {% endblock %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="bg-primary p-4 shadow-lg">
            <p>

                Ofejiro Agbaduta Prime is a software engineer, robotics engineer, and the creator of this calculator website. He studied mathematics at Ambrose Alli University and is very broad in the field of machine learning and computer vision. He is also a competent communicator and has a passion for teaching. <br>

                Ofejiro started working on this calculator website in his spare time while he was still a student. He wanted to create a calculator that was both easy to use and powerful. He also wanted to make sure that the calculator was accessible to everyone, regardless of their level of mathematical expertise. <br>

                In addition to his work on the calculator website, Ofejiro is also a passionate advocate for education. He believes that everyone should have access to quality education, regardless of their background. He is also a strong believer in the power of technology to improve education. <br>

                Ofejiro is a talented software engineer, a gifted communicator, and a passionate advocate for education. He is a valuable asset to the field of technology and education. <br>

                Here are some of the things that Ofejiro Agbaduta Prime has accomplished: <br>

                * He created a calculator website that is both easy to use and powerful. <br>
                * He made the calculator website accessible to everyone, regardless of their level of mathematical expertise. <br>
                * He is a passionate advocate for education.
                * He believes that everyone should have access to quality education, regardless of their background. <br>
                * He is a strong believer in the power of technology to improve education. <br>
                * He is a robotics engineer who has developed several robots that can perform a variety of tasks. <br>
                * He is also a machine learning expert who has developed several algorithms that can be used to solve a variety of problems. <br>
                * Ofejiro is a brilliant and versatile engineer who is making significant contributions to the fields of technology and education. <br>

                Ofejiro Agbaduta Prime is a rising star in the field of technology. He is a talented engineer with a passion for education. He is sure to make a significant impact on the world in the years to come.
            </p>
       </div>
    </div>
{% endblock %}

templates/algebra1.html
{% extends "base.html" %}
{% block title %} algebra {% endblock %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="bg-primary p-4 shadow-lg">
            <p>
                Algebra is a branch of mathematics that deals with the manipulation of symbols and the rules for manipulating these symbols in formulas. It is a unifying thread of almost all of mathematics. Elementary algebra deals with the manipulation of variables as if they were numbers and is therefore essential in all applications of mathematics.
                
                One example of an algebraic equation is the following:
                
                <br>
                
                x + 2 = 5
                
                <br>
                
                This equation states that the sum of x and 2 is equal to 5. This equation can be solved by subtracting 2 from both sides to get the following solution:
                
                <br>
                
                x = 3
                
                <br>
                
                Another example of an algebraic equation is the following:
                
                <br>
                
                x^2 - 5x + 6 = 0
                
                <br>
                
                This equation is called a quadratic equation. It can be solved using the quadratic formula to get the following solutions:
                
                <br>
                
                x = 3 or x = 2
                
                <br>
                
                Algebraic equations can be solved using a variety of methods, including the substitution method, the elimination method, and the quadratic formula. The method used to solve an algebraic equation depends on the type of equation and the desired solution.
                
                Here are some additional examples of algebraic equations:
                
                <br>
                
                * The equation for the area of a triangle is:
                
                <br>
                
                A = 1/2bh
                
                <br>
                
                where A is the area of the triangle, b is the base of the triangle, and h is the height of the triangle.
                
                * The equation for the volume of a cylinder is:
                
                <br>
                
                V = πr^2h
                
                <br>
                
                where V is the volume of the cylinder, π is a mathematical constant, r is the radius of the cylinder, and h is the height of the cylinder.
                
                * The equation for the speed of an object is:
                
                <br>
                
                v = d/t
                
                <br>
                
                where v is the speed of the object, d is the distance traveled by the object, and t is the time it takes the object to travel the distance.
                
                Algebra is used in a wide variety of applications, including physics, engineering, economics, and finance. It is a powerful tool for solving problems and making predictions.
            </p>
                
       </div>
    </div>
{% endblock %}

templates/algebra_form.html
{%  extends "base.html" %}
{% block title %} algebra form {% endblock %}
{% block body %}
      <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="form-container">
          <h3 class="mb-4 text-center">simplifying equations</h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="x">Simplify:</label>
              <input type="text" class="form-control" id="x" placeholder="Enter Equation to simplify" name="x">
            </div>
            <!-- <div class="form-group">
              <label for="y">Y:</label>
              <input type="text" class="form-control" id="y" placeholder="Enter Y">
            </div>
            <div class="form-group">
              <label for="z">Z:</label>
              <input type="text" class="form-control" id="z" placeholder="Enter Z">
            </div> -->
            <div class="text-center"> <!-- Center the submit button -->
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
          {% if result %}
              <h4 class="mt-4 text-center">The answer is: {{ result }}</h4>
          {% endif %}
        </div>
      </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script defer src="{% static '/js/script.js' %}"></script>
        <link rel="stylesheet" href="{% static '/css/design.css' %}">
    <title>{% block title %} calculator app {% endblock %}</title>
</head>
<body>
    <nav class="navbar  bg-dark  navbar-expand-lg bg-body-tertiary data-bs-theme="dark" " >
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Prime calculator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
              <a class="nav-link" href="{% url 'child:about' %}">About author</a>
              <a class="nav-link" href="#">Morn products</a>
              <a class="nav-link disabled">Report</a>
            </div>
          </div>
        </div>
    </nav>
    {% block body %}
    

    
    {% endblock %}
    <div class="footer bg-dark text-white py-4">
        <div class="container text-center">
          <div class="row">
            <div class="col-md-4">
              <h5>Contact:</h5>
              <p>08072430922</p>
            </div>
            <div class="col-md-4">
              <h5>Email:</h5>
              <p>agbadutaofejiro123@gmail.com</p>
            </div>
            <div class="col-md-4">
              <h5>Website Motto:</h5>
              <p>Making mathematics fun with the proper tools.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12 mt-3">
              <p>Any additional important information or links can be placed here.</p>
            </div>
          </div>
        </div>
    </div>
</body>
</html>

templates/calculus1.html
{% extends "base.html" %}
{% block title %} Calculus {% endblock %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="bg-primary p-4 shadow-lg">
            <p>
                A differential equation is an equation that contains one or more derivatives of an unknown function. The derivatives of the function define the rate of change of the function at a point. Differential equations are used in many fields, including physics, engineering, biology, and economics.
                
                One example of a differential equation is the following:
                
                <br>
                
                dy/dx = x
                
                <br>
                
                This equation states that the rate of change of the function y with respect to the variable x is equal to x. This equation can be solved using separation of variables to get the following solution:
                
                <br>
                
                y = x^2 + C
                
                <br>
                
                where C is an arbitrary constant.
                
                Another example of a differential equation is the following:
                
                <br>
                
                y'' + y = 0
                
                <br>
                
                This equation is called the harmonic oscillator equation. It describes the motion of a mass on a spring. The solution to this equation is given by the following formula:
                
                <br>
                
                y = A cos(t) + B sin(t)
                
                <br>
                
                where A and B are arbitrary constants.
                
                Differential equations can be solved using a variety of methods, including separation of variables, integrating factors, and power series solutions. The method used to solve a differential equation depends on the type of equation and the desired solution.
                
                Here are some additional examples of differential equations:
                
                <br>
                
                * The equation for the growth of a population is:
                
                <br>
                
                dN/dt = rN
                
                <br>
                
                where N is the population size, t is time, and r is the growth rate.
                
                * The equation for the motion of a falling object is:
                
                <br>
                
                m d^2x/dt^2 = -mg
                
                <br>
                
                where m is the mass of the object, g is the acceleration due to gravity, and x is the position of the object.
                
                * The equation for the flow of heat through a rod is:
                
                <br>
                
                k d^2T/dx^2 = -q
                
                <br>
                
                where k is the thermal conductivity of the rod, T is the temperature, and q is the heat flux.
                
                Differential equations are used in a wide variety of applications, including physics, engineering, biology, and economics. They are a powerful tool for modeling and predicting the behavior of systems.
            </p>
                
       </div>
    </div>
{% endblock %}

templates/calculus_form.html
{% extends "base.html" %}
{% block title %} Calculus Form {% endblock %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="form-container">
            <h3 class="mb-4 text-center">Differential Equation</h3>
            <form method="post"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="x">Input your Equation:</label>
                    <input type="text" class="form-control" id="x" placeholder="E.g 3*x + y**2" name="x">
                </div>
                <div class="form-group">
                    <label for="y">Order:</label>
                    <input type="text" class="form-control" id="order" placeholder="enter order 1,2,...n" name="order">
                </div>
                <div class="form-group">
                    <label for="z">Respect to:</label>
                    <input type="text" class="form-control" id="respect" placeholder="Enter x,y or z" name="respect">
                </div>
                <div class="text-center"> <!-- Center the submit button -->
                    <button type="submit" class="btn btn-primary" value="Add">Submit</button>
                </div>
            </form>
            {% if result %}
                <h4 class="mt-4 text-center">The answer is: {{ result }}</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/probability1.html
{% extends "base.html" %}
{% block title %} probability {% endblock %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="bg-primary p-4 shadow-lg">
            <p>
                Probability is a branch of mathematics that deals with the likelihood of events. It is expressed as a number in the range from 0 to 1, or, using percentage notation, in the range from 0% to 100%. The more likely it is that the event will occur, the higher its probability.
                
                One example of a probability problem is the following:
                
                <br>
                
                What is the probability of flipping a coin and getting heads?
                
                <br>
                
                There are two possible outcomes when flipping a coin: heads or tails. Since heads is one of the two possible outcomes, the probability of getting heads is 1/2 or 50%.
                
                Another example of a probability problem is the following:
                
                <br>
                
                What is the probability of rolling a 6 on a standard die?
                
                <br>
                
                There are 6 possible outcomes when rolling a die: 1, 2, 3, 4, 5, or 6. Since 6 is one of the possible outcomes, the probability of rolling a 6 is 1/6 or 16.67%.
                
                Probability is used in many different fields, including statistics, gambling, and risk assessment. It is a powerful tool for making predictions about the future.
            </p>
                
       </div>
    </div>
{% endblock %}

templates/probability_form.html
{%  extends "base.html" %}
{% block title %} probability form {% endblock %}
{% block body %}
      <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="form-container">
          <h3 class="mb-4 text-center">probability</h3>
          <form method="post">
            {% csrf_token %}

            <div class="form-group">
              <label for="x">Number of desired outcome:</label>
              <input type="text" class="form-control" id="x" placeholder="Enter desired outcome" name="x">
            </div>
            <div class="form-group">
              <label for="y">Total number of possible outcome:</label>
              <input type="text" class="form-control" id="y" placeholder="Enter total outcome" name="y">
            </div>
            <div class="text-center"> <!-- Center the submit button -->
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
          {% if result %}
              <h4 class="mt-4 text-center">The answer is: {{ result }}</h4>
          {% endif %}
        </div>
      </div>
{% endblock %}

templates/statistic_form.html
{%  extends "base.html" %}
{% block title %} statictics form {% endblock %}
{% block body %}
      <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="form-container">
          <h3 class="mb-4 text-center">median</h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="x">Insert numbers:</label>
              <input type="text" class="form-control" id="x" placeholder="E.g 3 6 7 8" name="x">
            </div>
            <div class="text-center"> <!-- Center the submit button -->
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
          {% if result %}
              <h4 class="mt-4 text-center">The answer is: {{ result }}</h4>
          {% endif %}
        </div>
      </div>
{% endblock %}

templates/statistics1.html
{% extends "base.html" %}
{% block title %} statistics {% endblock %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="bg-primary p-4 shadow-lg">
            <p>
                <p>
                    Statistics is the study of the collection, organization, analysis, interpretation, and presentation of data. It is a powerful tool that can be used to understand and make predictions about the world around us.
                    
                    Here are two examples of how statistics can be used:
                    
                    * A company might use statistics to track sales data and identify trends. This information could be used to make decisions about product development, marketing, and pricing.
                    * A government might use statistics to track population data and identify areas of need. This information could be used to allocate resources and develop policies to improve the lives of citizens.
                    
                    Statistics is a versatile tool that can be used in a wide variety of settings. It is a valuable skill for anyone who wants to understand the world around them and make informed decisions.
                    
                    Here are some additional examples of how statistics can be used:
                    
                    * In medicine, statistics can be used to track the effectiveness of treatments and identify new diseases.
                    * In finance, statistics can be used to track the performance of investments and identify risks.
                    * In sports, statistics can be used to track the performance of athletes and identify trends.
                    
                    Statistics is a powerful tool that can be used to understand and make predictions about the world around us. It is a valuable skill for anyone who wants to make informed decisions.
                </p>
                    
            </p>
       </div>
    </div>
{% endblock %}

templates/web.html
{% extends "base.html"%}
{% load static %}


    {% block body%}
      
        

              <!-- <div class="design">
                  <h1>Hebrews.Ai</h1>
              </div>
      -->
              <!-- <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown button
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </div>
      -->
          <div class="container">
            <div class="col1 d-flex flex-column mb-3 pt-2">
                  <div class="dcol shadow"> calculus</div>
                  <div class="dcol shadow"> algebra </div>
                  <div class="dcol shadow"> statistic </div>
                  <div class="dcol shadow"> probability</div>
            </div>
            <div class="col2 logos">
              <div class="image-grid box log">
                  <div class="logo">
                      <a href="{% url 'child:cal1' %}">
                        <img src="{% static 'images/1-calculus.jpeg' %}" alt="" class="image">
                      </a>
                  </div>
                  <div class="logo">
                      <a href="{% url 'child:alg1'  %}">
                        <img src="{% static 'images/algebra.jpeg' %}" alt="" class="image">
                      </a>
                  </div>
                  <div class="logo">
                      <a href="{% url 'child:pro1'  %}">
                      <img src="{% static 'images/probability.jpg' %}" alt="" class="image">
                      </a>
                  </div>
                  <div class="logo">
                    <a href="{% url 'child:sta1'  %}">
                      <img src="{% static 'images/statistics.jpeg' %}" alt="" class="image">
                    </a>
                  </div>
                  <div class="logo">
                    <a href="{% url 'child:cal2'%}">
                      <img src="{% static 'images/calculus2.jpeg' %}" alt="" class="image">
                    </a>
                  </div>
                  <div class="logo">
                    <a href="{% url 'child:alg2'%}">
                      <img src="{% static 'images/algebra2.jpg' %}" alt="" class="image">
                    </a>
                  </div>
                  <div class="logo">
                    <a href="{% url 'child:pro2'%}">
                      <img src="{% static 'images/probability2.webp' %}" alt="" class="image">
                    </a>
                  </div>
                  <div class="logo">
                    <a href="{% url 'child:sta2'%}">
                      <img src="{% static 'images/statics2.jpg' %}" alt="" class="image">
                    </a>
                  </div>
              </div>

              </div>
            </div>

    {% endblock %}